### ISSUE TITLE
Invalid character in php-extras.el

### ISSUE THREAD

**Issue by svenpanne** [arnested/php-extras#18]
[Line 84 in php-extras.el](https://github.com/arnested/php-extras/blob/7d50d23be4c2206a2782f849961f27880674adf4/php-extras.el#L84) contains a form-feed character (ascii char 12), which my Emacs (25.2.1) doesn't like. This problem shows up if you e.g. add a PHP layer to spacemacs, see syl20bnr/spacemacs#5007.  The fix should be easy: Just remove that line...

**Comment by arnested** [comment]
Sorry for the late follow up.

The character is a page break and is often used in elisp files. See https://stackoverflow.com/questions/1576887/what-does-l-in-emacs-lisp-source-code-mean

I have a hard time believing that Spacemacs should have trouble with them and believe the problem described to have some other root cause.

I wouldn't have a problem removing the `^L`s from the source code (they are not that important to me so feel free to create a pull request), but I think some other problem is the the root cause.
